services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lacasa_root_password
      MYSQL_DATABASE: la_casa_gaudencia
      MYSQL_USER: lacasa_gaudencia
      MYSQL_PASSWORD: Godsbreath
    ports:
    - "3307:3306"        
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - test_demo_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: lacasa_gaudencia
      PMA_PASSWORD: Godsbreath
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
    - test_demo_network

volumes:
  mysql_data:

networks:
  test_demo_network:
    driver: bridge
